"""
Remediation Schema

Safe remediation suggestions with guardrails.
"""

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class RiskLevel(str, Enum):
    """Risk levels for remediation steps"""
    
    LOW = "low"             # Safe, reversible
    MEDIUM = "medium"       # Some risk, but manageable
    HIGH = "high"           # Requires approval, rollback plan
    CRITICAL = "critical"   # Production-impacting, needs escalation


class RemediationStep(BaseModel):
    """
    Single remediation action.
    
    Includes safety metadata for guardrails.
    """
    
    # Order
    step_number: int = Field(..., description="Step number in sequence")
    
    # Action
    action: str = Field(
        ...,
        description="Human-readable action description"
    )
    command: Optional[str] = Field(
        default=None,
        description="Actual command to run (if applicable)"
    )
    command_type: Optional[str] = Field(
        default=None,
        description="Type of command (kubectl, sql, bash, etc.)"
    )
    
    # Risk Assessment
    risk_level: RiskLevel = Field(
        ...,
        description="Risk level of this step"
    )
    risk_reasoning: str = Field(
        default="",
        description="Why this risk level was assigned"
    )
    requires_approval: bool = Field(
        default=False,
        description="True if human approval needed"
    )
    
    # Safety
    rollback_plan: Optional[str] = Field(
        default=None,
        description="How to undo this step"
    )
    rollback_command: Optional[str] = Field(
        default=None,
        description="Command to rollback"
    )
    pre_conditions: List[str] = Field(
        default_factory=list,
        description="Conditions to verify before running"
    )
    post_validation: Optional[str] = Field(
        default=None,
        description="How to verify step succeeded"
    )
    
    # Timing
    estimated_time: str = Field(
        default="1-2 minutes",
        description="Estimated time to complete"
    )
    
    # Dependencies
    depends_on: List[int] = Field(
        default_factory=list,
        description="Step numbers this depends on"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "step_number": 1,
                "action": "Rollback payment-service to v2.3.0",
                "command": "kubectl rollout undo deployment/payment-service -n payments",
                "command_type": "kubectl",
                "risk_level": "medium",
                "risk_reasoning": "Rollback is generally safe but will cause brief downtime",
                "requires_approval": False,
                "rollback_plan": "Re-deploy v2.3.1 if rollback causes issues",
                "rollback_command": "kubectl rollout undo deployment/payment-service -n payments",
                "pre_conditions": ["Verify v2.3.0 image is available"],
                "post_validation": "Check error rate returns to normal within 5 minutes",
                "estimated_time": "2-5 minutes"
            }
        }


class Remediation(BaseModel):
    """
    Complete remediation plan.
    
    Generated by Remediation Agent with guardrails applied.
    """
    
    # Identity
    id: str = Field(..., description="Unique remediation plan ID")
    investigation_id: str = Field(..., description="Parent investigation ID")
    root_cause_id: str = Field(..., description="Root cause this addresses")
    
    # Summary
    summary: str = Field(
        ...,
        description="Brief summary of remediation approach"
    )
    detailed_explanation: str = Field(
        default="",
        description="Detailed explanation of why this remediation"
    )
    
    # Steps
    steps: List[RemediationStep] = Field(
        ...,
        description="Ordered remediation steps"
    )
    total_steps: int = Field(
        default=0,
        description="Total number of steps"
    )
    
    # Risk Assessment
    total_risk_score: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="Overall risk score (0-1)"
    )
    highest_risk_step: Optional[int] = Field(
        default=None,
        description="Step number with highest risk"
    )
    requires_human_approval: bool = Field(
        default=False,
        description="True if any step requires approval"
    )
    
    # Timing
    estimated_resolution_time: str = Field(
        ...,
        description="Total estimated time"
    )
    
    # Historical Context
    based_on_runbook: Optional[str] = Field(
        default=None,
        description="Runbook this is based on"
    )
    similar_past_incident: Optional[str] = Field(
        default=None,
        description="Similar past incident ID"
    )
    past_success_rate: Optional[float] = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Success rate of this fix in past"
    )
    
    # Warnings
    warnings: List[str] = Field(
        default_factory=list,
        description="Warnings about this remediation"
    )
    blocked_suggestions: List[str] = Field(
        default_factory=list,
        description="Suggestions blocked by guardrails"
    )
    
    # Metadata
    generated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="When this plan was generated"
    )
    guardrails_applied: List[str] = Field(
        default_factory=list,
        description="Guardrails that were applied"
    )
    
    class Config:
        json_schema_extra = {
            "example": {
                "id": "rem-001",
                "investigation_id": "inv-12345",
                "root_cause_id": "rca-001",
                "summary": "Rollback deployment and increase connection pool size",
                "steps": [],
                "total_steps": 3,
                "total_risk_score": 0.35,
                "highest_risk_step": 2,
                "requires_human_approval": False,
                "estimated_resolution_time": "10-15 minutes",
                "based_on_runbook": "runbook-connection-pool",
                "similar_past_incident": "INC-2024-0892",
                "past_success_rate": 0.95,
                "warnings": ["Brief downtime expected during rollback"],
                "guardrails_applied": ["require_rollback_plan", "validate_commands"]
            }
        }


class RemediationExecution(BaseModel):
    """
    Execution tracking for remediation.
    
    Tracks which steps have been executed and their results.
    """
    
    remediation_id: str
    started_at: datetime
    completed_at: Optional[datetime] = None
    
    # Step execution
    current_step: int = 0
    steps_completed: List[int] = Field(default_factory=list)
    steps_failed: List[int] = Field(default_factory=list)
    steps_skipped: List[int] = Field(default_factory=list)
    
    # Results
    execution_logs: List[dict] = Field(default_factory=list)
    success: Optional[bool] = None
    failure_reason: Optional[str] = None
    
    # Approval tracking
    approvals_received: List[dict] = Field(default_factory=list)
    awaiting_approval_step: Optional[int] = None
